version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing requirements
          command: apt-get update && apt-get install -y build-essential gcc libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - run:
          name: Building
          command: make

  lint:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing requirements
          command: apt-get update && apt-get install -y build-essential gcc wget libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - run:
          name: Install OCLint
          command: cd /tmp && wget -c https://github.com/oclint/oclint/releases/download/v0.13.1/oclint-0.13.1-x86_64-linux-4.4.0-112-generic.tar.gz -O - | tar -xz

      - run:
          name: Linting
          command: /tmp/oclint-0.13.1/bin/oclint `find -name *.c` -- -c

workflows:
  version: 2
  build_and_lint:
    jobs:
      - build
      - lint
