version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing requirements
          command: apt-get update && apt-get install -y build-essential gcc libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - run:
          name: Building
          command: make

  lint:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing requirements
          command: apt-get update && apt-get install -y build-essential gcc wget libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

      - run:
          name: Install OCLint
          command: cd /tmp && wget -c https://github.com/oclint/oclint/releases/download/v0.13.1/oclint-0.13.1-x86_64-linux-4.4.0-112-generic.tar.gz -O - | tar -xz

      - run:
          name: Linting
          command: /tmp/oclint-0.13.1/bin/oclint -disable-rule=ShortVariableName `find -name *.c` -- -c

  doc:
    docker:
      - image: debian:stretch

    steps:
      - run:
          name: Installing requirements
          command: apt-get update && apt-get install -y build-essential wget git cmake python flex bison

      - run:
          name: Installing Doxygen
          command: cd /tmp && git clone https://github.com/doxygen/doxygen.git && cd doxygen && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && make install && cd ~

      - checkout

      - run:
          name: Replace doc output directory
          command: sed 's/OUTPUT_DIRECTORY       = .\/doc/OUTPUT_DIRECTORY       = \/tmp\/artifacts\/doc/g' Doxyfile > Doxyfile.ci

      - run:
          name: Generate doc
          command: mkdir -p /tmp/artifacts/ && /tmp/doxygen/build/bin/doxygen Doxyfile.ci

      - add_ssh_keys

      - run:
          name: Deploy doc
          command: scp -o StrictHostKeyChecking=no -r /tmp/artifacts/doc/html/* $SSH_USER@$SSH_HOST:~/doc

workflows:
  version: 2
  build_lint_doc:
    jobs:
      - build
      - lint:
          requires:
            - build
      - doc:
          filters:
            branches:
              only: features/#16-ecs-engine
